### PR TITLE
Poisson Regression

### PR DESCRIPTION
**Pull request by pachadotdev**
Hi @MatthieuStigler 

I created a decent function to fit Poisson regression with FEs, offset and/or cluster.

This is how it works
```
load_all()
fit1 = fepois(mpg ~  wt | cyl, offset = ~qsec, cluster = ~am, data = mtcars)
summary(fit1)
```

This was motivated in part, by https://github.com/lrberge/fixest/issues/286, therefore I listed @paulofelipe as a contributor, because even when the functions here can use formulas and all the fancy stuff, the base is Paulo's code and some of the existing functions in the lfe package (the simplifications, optimizations and dis-arrangements are mine).

Would you like to add this to lfe or it should be a part of a separate package? I was thinking about a separate package, but it would be good to keep lfe running, even if most functions are in strict maintenance mode.

### CODE REVIEW

**Comment by MatthieuStigler** [comment]
Hi Pacha!

Nice work! I think it is really up to you. In fact, it feels like you are so more knowledgable and involved than me that it would make sense that you become the maintainer of lfe? I feel it would better in your hands, what do you think?

**Comment by pachadotdev** [comment]
hi @MatthieuStigler 
happy to maintain it

**Comment by pachadotdev** [comment]
hi @MatthieuStigler 
I hope this post finds you well. I shall send you a separate email explaining my delays.
I compared lfe's fepois against stata, fixest, and base R and it works correctly, no more "it worked on my laptop"

see this time gain, there's also memory gains that make it feasible to estimate models with micro level data, even when fepois is not "the best" function (the data for the example has 28,000 rows and 700 fixed effects)

Screenshot from 2023-04-03 10-37-05

**Comment by MatthieuStigler** [comment]
nice, congrats!

and I guess estimates are the same? Even (non-clustered) ses?

**Comment by pachadotdev** [comment]
> 

thanks! yes, I compared against base R + sandwich, and for the IID and non-IID case the estimates, std errors, and t values are the same (also same as in Stata 11)

**Comment by pachadotdev** [comment]
@MatthieuStigler before merging I still need to fix some "1: In xtfrm.data.frame(x) : cannot xtfrm data frames" errors that happen with some data

**Comment by pachadotdev** [comment]
all good now

**Pull request merged**
