### PR TITLE
fix issue #3

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by MatthieuStigler** [comment]
thanks! Did you run `R CMD CHECK` ? I am getting a ton of errors in the test files, mostly due to the new indenting?

**Comment by pachadotdev** [comment]
> thanks! Did you run `R CMD CHECK` ? I am getting a ton of errors in the test files, mostly due to the new indenting?

@MatthieuStigler yes! I got 0 errors and 0 warnings

**Comment by MatthieuStigler** [comment]
That is surprising! Maybe you left the `tests/xxx.Rout` files on your local copy? Or did not commit the updated `tests/xxx.Rout.save` ones?

As a typical example, in `tests/bctest.R` the line `alpha=getfe(est)` was changed into `alpha <- getfe(est)`, but not in `tests/bctest.Rout.save`, hence `R CMD check` should create a warning!?

**Comment by pachadotdev** [comment]
@MatthieuStigler I de-styled the tests, that should work

**Comment by MatthieuStigler** [comment]
It passed the test now without any issue, great, thanks a lot!

**Pull request merged**
